// html.go: html/javascript/css to convert generated markdown to html

package catalog

// CSS from https://github.com/KrauseFx/markdown-to-html-github-style/blob/master/style.css (MIT License)
const script = `<script src="/livereload.js?port=6900&mindelay=10&v=2" data-no-instant defer></script>`

const header = `
<!doctype html>
<html lang="en"><head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sysl Catalog</title>
</head>
<body>
<div id='content'>
`

const endTags = `</div>
</body>
</html>`

const favicon = `AAABAAEAQEAAAAEAIAAoQgAAFgAAACgAAABAAAAAgAAAAAEAIAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmPfUZaDzvUWg68xYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbT3zFWk88HdpPPDQaTzxw2Y99RkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wFoPfE2ZzvwRWpA6gwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABnPO8vaj3vpGk88PhpPPD/aTzwqlUr/wYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGo8715pPPDxaTzvs2o8715gQP8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQ39BdpO/CbaTzw/Gk88P9pPPD/aT3wuVUr/wYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaDvwVmk88P9pPPD/aTzw6mo974JmRO4PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGo78FdpPPDxaTzw/2k88P9pPPD/aTzv5mZA8hQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpPPCnaTzw/2k88P9pPPD/aTzw62g98GkAAP8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZjP/BWg88ZBpPPD/aTzw/2k88P9pPPD/aTzw/2g98FMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZzvwNGk88P9pPPD/aTzw/2k88P9pPPD/ajzwumw76xoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgED/BGk78KxpPPD/aTzw/2k88P9pPPD/aTzw/2k88MkAAP8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wFpPPDpaTzw/2k88P9pPPD/aTzw/2k88P9pPPDkaz3wMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAD/Amk88KVpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPFaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTzwx2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88PRrPu8+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGk98HVpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPDyYED/CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGg88KtpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw8mo68TUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGs98DJpPPD5aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzvtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpPPC2aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPHlZj31GQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpPO/EaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2o88HsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTzw2Wk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88L8AAP8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoPfFHaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9qO/BXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZjrwI2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aD3waQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTzwuGk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/ajvvQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGk88JlpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88O1pPPARAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbT3zFWk88PtpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2g98jsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGg98UdpPPD8aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aT3whgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGk872FpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9nO/BFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG037Q5iO+sNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGg78VtpPPD0aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88OptSf8HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpPfCXaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/ajzvXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqQOoMaj3vgmk88OJpPPD/aTzw/2k88OloPPCraj3vcWg98UdqO+9SaT3wdWk88MhpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aD3xWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTzwyWk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88IgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmPfUZaTzv1Wk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88L8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGg88ONpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTzwwGk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD8bTftDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpPPD2aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw+ms28hMAAAAAAAAAAAAAAAAAAAAAajzuTWk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2o68EYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTzw+2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPBmAAAAAAAAAAAAAAAAAAAAAGk98bFpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9qPe+CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGk88PFpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzv1QAA/wEAAAAAAAAAAAAA/wFpPPDraTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzvtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpO/DfaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9oPfBTAAAAAAAAAABoOvMWaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k98MoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAajzwumk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw4WI76w0AAAAAZDf0F2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPDeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGo875FpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9qPPCYAAAAAG098xVpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqPfBUaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k98GQAAP8BaTzw72k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2o88OgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZkDyFGk88PxpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD5ajzuTWk88LtpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9qPPDXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpPPC4aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88PlpPPDPaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aT3xsQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaD3xWGk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2o874AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFVV/wNpPfDbaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pO/E4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTzvYWk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88O9oPPCEZzryOWc87y9pPfFcaTzxw2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pO/DfgAD/AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wFoO/DBaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k87+ZqOfEkAAAAAAAAAAAAAAAAAAAAAAAAAABqPe9xaTzw/Wk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzwdwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTzwImk88O5pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9oPfBTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGk98Y9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzv5nRG6AsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABnO/FKaTzw/Wk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD7VSv/BgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABiO+sNaTzw9mk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2o98GUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGg873NpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw+QAA/wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGk88LdpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2g88M1VVf8DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTvvgWk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9nO/A0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpPPGhaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88PtrPfAyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoO/F9aTzw/mk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTvwrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTzwnmk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9qPPCMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGg78VtpPPD4aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9oO/FsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGk98KhpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPDrZkTuDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaT3vP2k88O1pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/Gg871EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoPPCraTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aDzxbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpO/InaTzw2Wk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPDyZjrwIwAAAAAAAAAAAAAAAAAAAAAAAAAAaT3wl2k88P9pPPD/aTzw/2k88P9pPPD/aTzw8mpA6gwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGZE7g9pPfGxaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88LYAAAAAAAAAAAAAAAAAAAAAAAAAAGo88HtpPPD/aTzw/2k88P9pPPD/aTzw/2o98LUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AWg78X1pPPD9aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/ZzryOQAAAAAAAAAAAAAAAAAAAABoPO9AaTzw/2k88P9pPPD/aTzw/2k88P9pPfGPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZzvxSmk88PBpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k876IAAAAAAAAAAAAAAAAAAAAAbUn/B2k88OdpPPD/aTzw/2k88P9pPPD/aT3wiwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABrO+0raTzw3mk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPDtVVX/AwAAAAAAAAAAAAAAAAAAAABpO+9waTzw/2k88P9pPPD/aTzw/2k88KoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGY99RlpPO/VaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2g67iwAAAAAAAAAAAAAAAAAAAAAgAD/Amk877NpPPD/aTzw/2k88P9pPPDngAD/AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbT3zFWk88dRpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9qPfBUAAAAAAAAAAAAAAAAAAAAAAAAAABxOeMJaTzvlGk88P5pPPD/aTzw/2g870AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmPO4eaTzx5Wk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aT3wZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABnPfMqaT3wi2o88MtqPPCpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGg870BpPPD9aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2o98GUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaT3wl2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPe9QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGhA7yBpPPD7aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/azzyJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTzvs2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw6gAA/wEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGo8729pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k98JcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpO/E4aTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9oPfE2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAajnxJGk88P9pPPD/aTzw/2k88P9pPPD/aTzw/2k88P9qPfC1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGZA8hRpPPD/aTzw/2k88P9pPPD/aTzw/2k88P9pPPD5aDruLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpPPAiaTzw/2k88P9pPPD/aTzw/2k88P9pPPD/aTzxfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAajrxNWk88P9pPPD/aTzw/2k88P9pPPD/aTzvs1VV/wMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGg78VtpPPD/aTzw/2k88P9pPPD/aTvwzmI76w0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoPPGQaTzw/2k88P9pPPD/ajzwy2s28hMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTzwx2k88P9pPPD/aTzvtGI76w0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZkDyFGk88PtpPPD+aTzwiIAA/wIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGo98GVpPPDZaz7vPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoPfFHYED/CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////////4/////////8H/w///////A//wf/////wH//gf////+A///Af////gH//8A////8Af//wB////gD///gD///+AP//+AH///wB///4AP///AH///gAf//4Af//8AB///gB///wAD//8AH//+AAP//wAf+fwAAf//AB/AAAAB//8AH4AAAAH//wAfgAAAAP//AA8AAAAA//8ADwAAAAD//wAGAAAAAP//AAYAAAAA//8AAgAAAAD//wACAAAAAP//AAAAAAAA//8AAAAAAAD//4AAAAAAAP//gAAAAAAA//+AAAAAAAD//8AAAAAAAP//wAAAD4AB///gAAAfwAH///AAAB/AA///+AAAH+AD///8AAAf4Af///4AAB/gD////wAAD+AP////gAAH4B/////AAAPgH////+AAA+A/////8AAB4D/////8AAHgP/////4AAPA//////wAA8B//////gAD4H//////AAP4f/////+AA/9//////8AD////////wAP////////gA////////+AH////////4Af////////gD////////+AP////////4B/////////gH////////+A/////////4H/////////g/////////8H/////////x//////////P///////////////8=`
const flashing = `
<style type="text/css">
/* Firefox old*/
@-moz-keyframes blink {
    0% {
        opacity:1;
    }
    50% {
        opacity:0;
    }
    100% {
        opacity:1;
    }
} 

@-webkit-keyframes blink {
    0% {
        opacity:1;
    }
    50% {
        opacity:0;
    }
    100% {
        opacity:1;
    }
}
/* IE */
@-ms-keyframes blink {
    0% {
        opacity:1;
    }
    50% {
        opacity:0;
    }
    100% {
        opacity:1;
    }
} 
/* Opera and prob css3 final iteration */
@keyframes blink {
    0% {
        opacity:1;
    }
    50% {
        opacity:0;
    }
    100% {
        opacity:1;
    }
} 
.blink-image {
    -moz-animation: blink normal 1s infinite ease-in-out; /* Firefox */
    -webkit-animation: blink normal 1s infinite ease-in-out; /* Webkit */
    -ms-animation: blink normal 1s infinite ease-in-out; /* IE */
    animation: blink normal 1s infinite ease-in-out; /* Opera and prob css3 final iteration */
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
	
}

</style>
`

const style = `
<style type="text/css">


body {
  font: 400 16px/1.5 "Helvetica Neue", Helvetica, Arial, sans-serif;
  color: #111;
  background-color: #fdfdfd;
  -webkit-text-size-adjust: 100%;
  -webkit-font-feature-settings: "kern" 1;
  -moz-font-feature-settings: "kern" 1;
  -o-font-feature-settings: "kern" 1;
  font-feature-settings: "kern" 1;
  font-kerning: normal;
  padding: 30px;
}

@media only screen and (max-width: 600px) {
  body {
    padding: 5px;
  }

  body > #content {
    padding: 0px 20px 20px 20px !important;
  }
}

body > #content {
  margin: 0px;
  max-width: 900px;
  border: 1px solid #e1e4e8;
  padding: 10px 40px;
  padding-bottom: 20px;
  border-radius: 2px;
  margin-left: auto;
  margin-right: auto;
}

hr {
  color: #bbb;
  background-color: #bbb;
  height: 1px;
  flex: 0 1 auto;
  margin: 1em 0;
  padding: 0;
  border: none;
}

/**
 * Links
 */
a {
  color: #0366d6;
  text-decoration: none; }
  a:visited {
    color: #0366d6; }
  a:hover {
    color: #0366d6;
    text-decoration: underline; }

pre {
  background-color: #f6f8fa;
  border-radius: 3px;
  font-size: 85%;
  line-height: 1.45;
  overflow: auto;
  padding: 16px;
}

/**
  * Code blocks
  */

code {
  background-color: rgba(27,31,35,.05);
  border-radius: 3px;
  font-size: 85%;
  margin: 0;
  word-wrap: break-word;
  padding: .2em .4em;
  font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,Courier,monospace;
}

pre > code {
  background-color: transparent;
  border: 0;
  display: inline;
  line-height: inherit;
  margin: 0;
  overflow: visible;
  padding: 0;
  word-wrap: normal;
  font-size: 100%;
}


/**
 * Blockquotes
 */
blockquote {
  margin-left: 30px;
  margin-top: 0px;
  margin-bottom: 16px;
  border-left-width: 3px;
  padding: 0 1em;
  color: #828282;
  border-left: 4px solid #e8e8e8;
  padding-left: 15px;
  font-size: 18px;
  letter-spacing: -1px;
  font-style: italic;
}
blockquote * {
  font-style: normal !important;
  letter-spacing: 0;
  color: #6a737d !important;
}

/**
 * Tables
 */
table {
  border-spacing: 2px;
  display: block;
  font-size: 14px;
  overflow: auto;
  width: 100%;
  margin-bottom: 16px;
  border-spacing: 0;
  border-collapse: collapse;
}

td {
  padding: 6px 13px;
  border: 1px solid #dfe2e5;
}

th {
  font-weight: 600;
  padding: 6px 13px;
  border: 1px solid #dfe2e5;
}

tr {
  background-color: #fff;
  border-top: 1px solid #c6cbd1;
}

table tr:nth-child(2n) {
  background-color: #f6f8fa;
}

/**
 * Others
 */

img {
  max-width: 100%;
}

p {
  line-height: 24px;
  font-weight: 400;
  font-size: 16px;
  color: #24292e; }

ul {
  margin-top: 0; }

li {
  color: #24292e;
  font-size: 16px;
  font-weight: 400;
  line-height: 1.5; }

li + li {
  margin-top: 0.25em; }

* {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
  color: #24292e; }

a:visited {
  color: #0366d6; }

h1, h2, h3 {
  border-bottom: 1px solid #eaecef;
  color: #111;
  /* Darker */ }
</style>`
