name: Build Docs
on:
  push:
    branches: [ master ]

jobs:
  gen-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Gen Docs
      if: "!contains(github.event.head_commit.message, 'skip-ci')"
      run: make docker-compose
    - name: Commit files
      run: |
        git config --local user.email "syslbot@anz.com"
        git config --local user.name "SyslBot"
        git add .
        git commit -m "Regenerate docs [skip-ci]" && echo ::set-env name=can_push::1 || echo "No changes to docs"
    - name: Push changes
      if: env.can_push == 1
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
