name: Gen Docs
on:
  push:
    branches: [ master ]

jobs:
  gen-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Gen Docs
      if: "!contains(github.event.head_commit.message, 'skip-ci')"
      run: make docker-mermaid-run
    
    - name: Publish Docs
      id: deploy-netlify-preview
      uses: netlify/actions/cli@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --prod --dir=demo/html --message="${{ github.ref }}@${{ github.sha }}"

